-- Tabla city
ALTER TABLE city
ADD CONSTRAINT FK_city_country FOREIGN KEY (country_id)
REFERENCES country(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

-- Tabla postcode
ALTER TABLE postcode
ADD CONSTRAINT FK_postcode_city FOREIGN KEY (city_id)
REFERENCES city(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

-- Tabla user
ALTER TABLE user
ADD CONSTRAINT FK_user_role FOREIGN KEY (role_id)
REFERENCES role(id)
ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT FK_user_city FOREIGN KEY (city_id)
REFERENCES city(id)
ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT FK_user_postcode FOREIGN KEY (postcode_id)
REFERENCES postcode(id)
ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT FK_user_country FOREIGN KEY (country_id)
REFERENCES country(id)
ON DELETE RESTRICT ON UPDATE CASCADE;

-- Tabla media
ALTER TABLE media
ADD CONSTRAINT FK_media_user FOREIGN KEY (user_id)
REFERENCES user(id)
ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_media_report FOREIGN KEY (report_id)
REFERENCES report(id)
ON DELETE SET NULL ON UPDATE CASCADE;

-- Tabla report
ALTER TABLE report
ADD CONSTRAINT FK_report_user FOREIGN KEY (user_id)
REFERENCES user(id)
ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_report_admin FOREIGN KEY (admin_id)
REFERENCES user(id)
ON DELETE SET NULL ON UPDATE CASCADE;

-- Tabla statistic
ALTER TABLE statistic
ADD CONSTRAINT FK_statistic_admin FOREIGN KEY (admin_id)
REFERENCES user(id)
ON DELETE CASCADE ON UPDATE CASCADE;

-- Tabla tracking
ALTER TABLE tracking
ADD CONSTRAINT FK_tracking_report FOREIGN KEY (report_id)
REFERENCES report(id)
ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_tracking_user FOREIGN KEY (user_id)
REFERENCES user(id)
ON DELETE CASCADE ON UPDATE CASCADE;

-- Tabla history
ALTER TABLE history
ADD CONSTRAINT FK_history_user FOREIGN KEY (user_id)
REFERENCES user(id)
ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_history_report FOREIGN KEY (report_id)
REFERENCES report(id)
ON DELETE CASCADE ON UPDATE CASCADE;
